### ISSUE TITLE
Scale factor confusion

### ISSUE THREAD

**Issue by MartinWickman** [Liagson/ConcaveHullGenerator#5]
Sorry to bring this up years later, but I'm trying to make sense of the scaleFactor. When I run the code, the number of points it finds doesn't always increase when the scaleFactor increases. Lets say I try these calls:

```
getNearByPoints( scaleFactor=16).Count  // 100 points
getNearByPoints( scaleFactor=17).Count  // 120 points
getNearByPoints( scaleFactor=18).Count  // 105 points (!)
```

Is that correct? From what I gather, the getBoundary() method should create a bounding box around the line (and the box size is determined by the scale factor). So, I mean, it should always find more points if the scale increases?

Also I'm sooo confused about these lines. Particularly why you *divide* with scaleFactor. Doesn't that make the box smaller?

```
        double min_x_position = Math.Floor(Math.Min(aNode.x, bNode.x) / scaleFactor);
        double min_y_position = Math.Floor(Math.Min(aNode.y, bNode.y) / scaleFactor);
        double max_x_position = Math.Floor(Math.Max(aNode.x, bNode.x) / scaleFactor);
        double max_y_position = Math.Floor(Math.Max(aNode.y, bNode.y) / scaleFactor);
```

Also, is there a reason why the scaleFactor is an `int` rather than a `double`? In my case (with geo coords), most points are very close to each (15.111 and 15.112) other so scaleFactor doesn't seem to do any difference at all, since getNearByPoint pretty much always returns all points for comparison (since 1 is the lowest scaleFactor).

https://github.com/Liagson/ConcaveHullGenerator/blob/16d5e629e41b3e64e425642849c67dd901f910d7/Assets/src/HullFunctions.cs#L99

**Comment by Liagson** [comment]
Hi Martin,
Looks like I messed up bad with the `scaleFactor ` logic. I'll try this week to take a look at the code, remember what it does and I'll fix the issue as soon as I can. Regarding the `scaleFactor` being an int: you are more than right, it should be a double (I'll change it too!)
Sorry for the inconvenience :(

**Comment by Liagson** [comment]
Hmmm, it **MIGHT** have taken me way less than expected. 
I've pushed a (possible) fix into [fix/scale-factor-refactor](https://github.com/Liagson/ConcaveHullGenerator/tree/fix/scale-factor-refactor) branch. Could you give it a look to see if it works fine for you?  It _looks_ like it's working for me in my demo scene, but who knows! Let me also know if there is a visible drop in performance.

The fix: I hate whatever logic I wrote 8 years ago, so I deleted it all. Now we check if the nodes to be processed are contained within an ellipse (ellipse set by the two nodes that define the line + a third node that is half the distance between the other two nodes away) Scale factor just makes the ellipse bigger/smaller. Try playing around with a `scaleFactor` of  values [1, 2]. But just let me know whatever you find.

**Comment by MartinWickman** [comment]
That was quick :-) Yeah, I tried it and it definitely behaves as you would expect. Increasing scale uses more points for calculations. Great work.

**Comment by Liagson** [comment]
Cool! I'll merge the branch into master this weekend and add some documentation too.

(I'm also pondering if I should update the project for newer Unity versions)

**Comment by Liagson** [comment]
Changes merged into master + documentation updated. You can stop using that branch :)
